# Generated by Django 2.2.6 on 2024-06-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='date',
            new_name='visit_time',
        ),
    ]
