# Generated by Django 2.2.6 on 2024-06-20 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='client',
            name='card_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='card_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='second_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
