# Generated by Django 5.0.6 on 2024-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240619_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
