# Generated by Django 5.0.6 on 2024-06-20 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_client_birthday_points_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
