# Generated by Django 5.0.6 on 2024-06-20 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
