# Generated by Django 5.1.15 on 2026-08-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_client_id_alter_referral_id_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
